<?php

declare(strict_types=1);

namespace Lumnd\PlatoApiContract\Generation;

use Closure;
use InvalidArgumentException;
use Lumnd\PlatoApiContract\Contract\RouteConvention;

/** Fluent definition API for a framework implemented by PHP templates and optional helpers. */
final class TemplatePackBuilder
{
    /** @var list<TemplateArtifactDefinition> */
    private array $artifacts = [];

    /** @var array<string, object> */
    private array $helpers = [];

    /** @var list<Closure(\Lumnd\PlatoApiContract\Ir\ContractCollection): list<string>> */
    private array $validators = [];

    private string $definitionFingerprint = '';

    public function __construct(
        private readonly string $name,
        private readonly RouteConvention $routes,
        private readonly TemplateRenderer $templates,
    ) {
        if (preg_match('/^[a-z][a-z0-9_-]*$/', $name) !== 1) {
            throw new InvalidArgumentException('Invalid template pack name: ' . $name);
        }
    }

    /** @param string|callable(TemplateContext): string $path */
    public function file(
        string $template,
        string|callable $path,
        Ownership $ownership = Ownership::Generated,
        ?callable $variables = null,
    ): self {
        return $this->artifact(TemplateScope::Collection, $template, $path, $ownership, $variables);
    }

    /** @param string|callable(TemplateContext): string $path */
    public function eachApi(
        string $template,
        string|callable $path,
        Ownership $ownership = Ownership::Generated,
        ?callable $variables = null,
    ): self {
        return $this->artifact(TemplateScope::Api, $template, $path, $ownership, $variables);
    }

    /** @param string|callable(TemplateContext): string $path */
    public function eachOperation(
        string $template,
        string|callable $path,
        Ownership $ownership = Ownership::Generated,
        ?callable $variables = null,
    ): self {
        return $this->artifact(TemplateScope::Operation, $template, $path, $ownership, $variables);
    }

    public function helper(string $name, object $helper): self
    {
        $this->helpers[$name] = $helper;

        return $this;
    }

    /** @param callable(\Lumnd\PlatoApiContract\Ir\ContractCollection): list<string> $validator */
    public function validate(callable $validator): self
    {
        $this->validators[] = Closure::fromCallable($validator);

        return $this;
    }

    /** Include configuration or helper behaviour that changes generated bytes. */
    public function fingerprint(string $value): self
    {
        $this->definitionFingerprint = hash('sha256', $this->definitionFingerprint . "\0" . $value);

        return $this;
    }

    public function build(): TemplatePack
    {
        if ($this->artifacts === []) {
            throw new InvalidArgumentException('Template pack ' . $this->name . ' does not declare any artifacts.');
        }

        return new TemplatePack(
            $this->name,
            $this->routes,
            $this->templates,
            $this->artifacts,
            new TemplateHelpers($this->helpers),
            $this->validators,
            $this->definitionFingerprint,
        );
    }

    /**
     * @param string|callable(TemplateContext): string $path
     * @param callable(TemplateContext): array<string, mixed>|null $variables
     */
    private function artifact(
        TemplateScope $scope,
        string $template,
        string|callable $path,
        Ownership $ownership,
        ?callable $variables,
    ): self {
        if (preg_match('/^[a-z][a-z0-9_]*$/', $template) !== 1) {
            throw new InvalidArgumentException('Invalid artifact template name: ' . $template);
        }

        $pathResolver = is_string($path)
            ? static fn (TemplateContext $context): string => $path
            : Closure::fromCallable($path);

        $this->artifacts[] = new TemplateArtifactDefinition(
            $scope,
            $template,
            $pathResolver,
            $ownership,
            $variables === null ? null : Closure::fromCallable($variables),
        );

        return $this;
    }
}
