<?php

declare(strict_types=1);

namespace App\control;

use Lumnd\PlatoApiContract\Runtime\ApiContext;
use Lumnd\PlatoApiContract\Runtime\Dto;
use Lumnd\PlatoApiContract\Runtime\Input;
use plato\http\reply;
use plato\http\req;
use plato\http\resp;
use plato\http\route;
use plato\http\upload;
use plato\plato;
use plato\security\validate;

// @generated by lumnd/plato-api-contract; DO NOT EDIT.
final class ctl_user
{
    /** @var array<string, array{methods: list<string>, auth: string}> */
    public static array $actions = [
        'login' => [
            'methods' => ['POST'],
            'auth' => 'none',
        ],
        'get_user_info' => [
            'methods' => ['GET'],
            'auth' => 'required',
        ],
        'disable_account' => [
            'methods' => ['POST'],
            'auth' => 'required',
        ],
    ];

    public function login(): reply
    {
        $input = [
            'username' => req::json('username'),
            'password' => req::json('password'),
            'remember' => req::json('remember'),
        ];
        $validator = validate::make($input, [
            'username' => ['scalar', 'required'],
            'password' => ['scalar', 'required'],
            'remember' => ['scalar', 'regex_match[/^(1|0|true|false|on|off|yes|no)?$/i]'],
        ]);

        if ($validator->fails()) {
            return resp::json(['errors' => $validator->errors()], 422);
        }

        $request = new \Fixture\api\LoginReq(username: Input::text(Input::at($input, 'username')), password: Input::text(Input::at($input, 'password')), remember: Input::flag(Input::at($input, 'remember'), null));
        $response = \App\logic\user_login::handle(
            $request,
            new ApiContext(plato::$auth, array_values(route::segments())),
        );

        return resp::response(0, Dto::toArray($response, \Fixture\api\LoginResp::class));
    }

    public function get_user_info(): reply
    {
        $input = [
            'id' => route::segments()[0] ?? null,
        ];
        $validator = validate::make($input, [
            'id' => ['scalar', 'required', 'integer', 'min[1]'],
        ]);

        if ($validator->fails()) {
            return resp::json(['errors' => $validator->errors()], 422);
        }

        $request = new \Fixture\api\user_info_req(id: Input::integer(Input::at($input, 'id'), 0));
        $response = \App\logic\user_get_user_info::handle(
            $request,
            new ApiContext(plato::$auth, array_values(route::segments())),
        );

        return resp::response(0, Dto::toArray($response, \Fixture\api\user_info_resp::class));
    }

    public function disable_account(): reply
    {
        $input = [
            'id' => req::json('id'),
        ];
        $validator = validate::make($input, [
            'id' => ['scalar', 'required', 'integer', 'min[1]'],
        ]);

        if ($validator->fails()) {
            return resp::json(['errors' => $validator->errors()], 422);
        }

        $request = new \Fixture\api\UserInfoReq(id: Input::integer(Input::at($input, 'id')));
        $response = \App\logic\user_disable_account::handle(
            $request,
            new ApiContext(plato::$auth, array_values(route::segments())),
        );

        return resp::response(0, Dto::toArray($response, \Fixture\api\AccountResp::class));
    }
}
