<?php

declare(strict_types=1);

namespace App\control;

use Lumnd\PlatoApiContract\Runtime\ApiContext;
use Lumnd\PlatoApiContract\Runtime\Dto;
use Lumnd\PlatoApiContract\Runtime\Input;
use plato\http\reply;
use plato\http\req;
use plato\http\resp;
use plato\http\route;
use plato\http\upload;
use plato\plato;
use plato\security\validate;

// @generated by lumnd/plato-api-contract; DO NOT EDIT.
final class ctl_ping
{
    /** @var array<string, array{methods: list<string>, auth: string}> */
    public static array $actions = [
        'index' => [
            'methods' => ['GET'],
            'auth' => 'none',
        ],
    ];

    public function index(): reply
    {
        $input = [
            'message' => req::get('message'),
        ];
        $validator = validate::make($input, [
            'message' => ['scalar', 'required', 'minlength[1]', 'maxlength[100]'],
        ]);

        if ($validator->fails()) {
            return resp::json(['errors' => $validator->errors()], 422);
        }

        $request = new \Fixture\api\PingReq(message: Input::text(Input::at($input, 'message')));
        $response = \App\logic\ping_index::handle(
            $request,
            new ApiContext(plato::$auth, array_values(route::segments())),
        );

        return resp::response(0, Dto::toArray($response, \Fixture\api\PingResp::class));
    }
}
