<?php

declare(strict_types=1);

namespace Lumnd\PlatoApiContract\Platform\Plato;

use Lumnd\PlatoApiContract\Ir\ApiContract;
use Lumnd\PlatoApiContract\Ir\Operation;
use Lumnd\PlatoApiContract\Php\PhpExport;
use Lumnd\PlatoApiContract\Platform\Plato\View\ActionView;
use Lumnd\PlatoApiContract\Platform\Plato\View\ControllerView;

/**
 * Assembles the PlatoPHP controller from the platform strategies.
 *
 * The generator decides nothing about layout and nothing about behaviour: every runtime decision -
 * where a field is read, which validation rule applies, how the request DTO is built, how Logic is
 * reached and how the response is written - comes from a replaceable strategy, and the resulting
 * view model is written out by the `controller` and `action` templates.
 */
final class PlatoControllerGenerator
{
    public const MARKER = '// @generated by lumnd/plato-api-contract; DO NOT EDIT.';

    public function __construct(
        private readonly RequestSource $requests = new PlatoRequestSource(),
        private readonly ValidationRules $validation = new PlatoValidationRules(),
        private readonly DtoHydration $hydration = new PlatoDtoHydration(),
        private readonly LogicResolver $logic = new PlatoLogicResolver(),
        private readonly ResponseWriter $responses = new PlatoResponseWriter(),
    ) {
    }

    /**
     * The strategies in force, so that replacing one marks generated files as out of date.
     *
     * Content hashes catch it in the end anyway, but the manifest also records a fingerprint of the
     * configuration those bytes came from, and a swapped response writer is exactly that.
     */
    public function fingerprint(): string
    {
        return hash('sha256', implode("\0", [
            $this->requests::class,
            $this->validation::class,
            $this->hydration::class,
            $this->logic::class,
            $this->responses::class,
        ]));
    }

    public function view(ApiContract $api, PlatoConfig $config): ControllerView
    {
        $actions = [];
        $views = [];
        $imports = array_merge(
            $this->requests->imports(),
            $this->validation->imports(),
            $this->responses->imports(),
            [
                'Lumnd\\PlatoApiContract\\Runtime\\ApiContext',
                'plato\\http\\route',
                'plato\\plato',
            ],
        );

        foreach ($api->operations as $operation) {
            $actions[$operation->action] = [
                'methods' => [$operation->method],
                'auth' => $operation->auth->value,
            ];
            $view = $this->actionView($api, $operation, $config);
            $views[] = $view;
            $imports = array_merge($imports, $this->hydration->imports($operation));
        }

        $imports = array_values(array_unique($imports));
        sort($imports, SORT_STRING);

        return new ControllerView(
            namespace: $config->controllerNamespace,
            class: $config->controllerClass($api),
            marker: self::MARKER,
            imports: $imports,
            actionsCode: PhpExport::asArray($actions, 1),
            actions: $views,
        );
    }

    private function actionView(ApiContract $api, Operation $operation, PlatoConfig $config): ActionView
    {
        $inputs = [];
        $rules = [];
        foreach ($operation->requestFields as $field) {
            $inputs[$field->name] = $this->requests->expression($field, $operation);
            $rules = array_merge($rules, $this->validation->forField($field));
        }

        $symbol = $config->symbol($api, $operation);
        $responseData = $this->hydration->response($operation, '$response');

        return new ActionView(
            name: $operation->action,
            httpMethod: $operation->method,
            path: $operation->path->value,
            returnType: $this->responses->returnType(),
            inputs: $inputs,
            validatorExpression: $this->validation->validatorExpression('$input', PhpExport::asArray($rules, 2)),
            failureStatement: $this->validation->failureStatement('$validator', $config),
            requestExpression: $this->hydration->request($operation, '$input'),
            logicExpression: $this->logic->callExpression(
                $config,
                $symbol,
                '$request',
                'new ApiContext(plato::$auth, array_values(route::segments()))',
            ),
            responseExpression: $this->responses->expression(
                $api->envelope,
                $responseData,
                $operation->primaryResponse()->status,
            ),
        );
    }
}
